export { app, isFirebaseConfigured } from './src/config';
export { auth, signIn, signUp, signOut, resetPassword, reauthenticate, getFreshIdToken, subscribeToAuthState, getCurrentUser } from './src/auth';
export {
  db,
  getUserProfile,
  createUserProfile,
  updateUserProfile,
  subscribeToTrips,
  createTrip,
  updateTrip,
  archiveTrip,
  getItinerary,
  upsertItineraryDay,
  subscribeToNotifications,
  markNotificationRead,
  subscribeSavedPlaces,
  savePlace,
  unsavePlace,
  getChecklist,
  upsertChecklistItem,
  deleteChecklistItem,
  getCachedPlace,
  upsertCachedPlace,
  searchCachedPlaces,
  getTripReminderPrefs,
  setTripReminderPrefs,
  // Community: Public Profiles
  getPublicProfile,
  upsertPublicProfile,
  deletePublicProfile,
  updateProfileVisibility,
  // Community: Public Trips
  setTripVisibility,
  getPublicTrip,
  subscribePublicTrips,
  subscribePublicTripMembers,
  // Community: Join Requests
  submitTripJoinRequest,
  cancelTripJoinRequest,
  approveTripJoinRequest,
  rejectTripJoinRequest,
  subscribeMyJoinRequests,
  subscribeTripJoinRequestsForOwner,
  subscribeRequestsForTrip,
  getTripJoinRequestStatus,
  // Community: Travel Groups
  createTravelGroup,
  updateTravelGroup,
  getTravelGroup,
  subscribePublicTravelGroups,
  subscribeGroupMembers,
  submitGroupJoinRequest,
  approveGroupJoinRequest,
  rejectGroupJoinRequest,
  removeGroupMember,
  leaveGroup,
  subscribeGroupJoinRequestsForOwner,
  subscribeMyGroupJoinRequests,
  getGroupJoinRequestStatus,
  // Community: Nearby Travelers
  upsertNearbyTraveler,
  deleteNearbyTraveler,
  subscribeNearbyTravelers,
  subscribeDestinationTravelers,
  // Community: Activity Feed
  addFeedItem,
  subscribeActivityFeed,
  deleteFeedItem,
  updateOwnerPhotoInCommunityDocs,
  // Community: Block / Report
  blockUser,
  unblockUser,
  subscribeBlockList,
  isBlocked,
  reportContent,
} from './src/firestore';
export {
  storage,
  uploadProfilePhotoBase64,
  uploadProfilePhoto,
  uploadJournalPhoto,
  uploadTripCoverPhoto,
  deleteTripCoverPhoto,
} from './src/storage';
export {
  // Phase 2: Posts
  createPost,
  updatePost,
  deletePost,
  getPost,
  subscribePostsByAuthor,
  subscribeExplorePosts,
  getPostsByCountry,
  getTrendingPosts,
  getPostsByType,
  getPostsFromUsers,
  // Phase 2: Likes
  likePost,
  unlikePost,
  isPostLiked,
  // Phase 2: Comments
  addComment,
  editComment,
  deleteComment,
  subscribeComments,
  subscribeReplies,
  // Phase 2: Saved Posts
  savePost,
  unsavePost,
  isSavedPost,
  subscribeSavedPosts,
  // Phase 2: Journals
  createJournal,
  updateJournal,
  deleteJournal,
  getJournal,
  subscribeJournalsByAuthor,
  subscribeExploreJournals,
  likeJournal,
  unlikeJournal,
  isJournalLiked,
  // Phase 2: Follow
  followUser,
  unfollowUser,
  isFollowing,
  getFollowCounts,
  subscribeFollowers,
  subscribeFollowing,
  getFollowingIds,
  // Phase 2: Reputation
  getReputation,
  upsertReputation,
  // Phase 2: Social notifications
  createSocialNotification,
} from './src/posts';
export {
  directChatId,
  upsertUserLookup,
  searchUserByEmail,
  subscribeToDirectChats,
  getOrCreateDirectChat,
  subscribeToDirectMessages,
  sendDirectMessage,
  markDirectChatRead,
  subscribeToGroups,
  createGroup,
  completeGroupCreation,
  subscribeToGroupMessages,
  sendGroupMessage,
  markGroupRead,
  getGroup,
} from './src/chat';
