export { app, isFirebaseConfigured } from './src/config';
export { auth, signIn, signUp, signOut, resetPassword, subscribeToAuthState, getCurrentUser } from './src/auth';
export {
  db,
  getUserProfile,
  createUserProfile,
  updateUserProfile,
  subscribeToTrips,
  createTrip,
  updateTrip,
  archiveTrip,
  getItinerary,
  upsertItineraryDay,
  subscribeToNotifications,
  markNotificationRead,
  subscribeSavedPlaces,
  savePlace,
  unsavePlace,
  getChecklist,
  upsertChecklistItem,
  deleteChecklistItem,
  getCachedPlace,
  upsertCachedPlace,
  searchCachedPlaces,
  getTripReminderPrefs,
  setTripReminderPrefs,
} from './src/firestore';
export {
  storage,
  uploadProfilePhoto,
  uploadJournalPhoto,
  uploadTripCoverPhoto,
  deleteTripCoverPhoto,
} from './src/storage';
export {
  directChatId,
  upsertUserLookup,
  searchUserByEmail,
  subscribeToDirectChats,
  getOrCreateDirectChat,
  subscribeToDirectMessages,
  sendDirectMessage,
  markDirectChatRead,
  subscribeToGroups,
  createGroup,
  subscribeToGroupMessages,
  sendGroupMessage,
  markGroupRead,
  getGroup,
} from './src/chat';
