export { app, isFirebaseConfigured } from './src/config';
export { auth, signIn, signUp, signOut, resetPassword, deleteCurrentUser, reauthenticate, deleteAuthUser, subscribeToAuthState, getCurrentUser } from './src/auth';
export {
  db,
  getUserProfile,
  createUserProfile,
  updateUserProfile,
  subscribeToTrips,
  createTrip,
  updateTrip,
  archiveTrip,
  getItinerary,
  upsertItineraryDay,
  subscribeToNotifications,
  markNotificationRead,
  subscribeSavedPlaces,
  savePlace,
  unsavePlace,
  getChecklist,
  upsertChecklistItem,
  deleteChecklistItem,
  getCachedPlace,
  upsertCachedPlace,
  searchCachedPlaces,
  getTripReminderPrefs,
  setTripReminderPrefs,
  deleteAllUserData,
  // Community: Public Profiles
  getPublicProfile,
  upsertPublicProfile,
  deletePublicProfile,
  updateProfileVisibility,
  // Community: Public Trips
  setTripVisibility,
  getPublicTrip,
  subscribePublicTrips,
  subscribePublicTripMembers,
  // Community: Join Requests
  submitTripJoinRequest,
  cancelTripJoinRequest,
  approveTripJoinRequest,
  rejectTripJoinRequest,
  subscribeMyJoinRequests,
  subscribeTripJoinRequestsForOwner,
  subscribeRequestsForTrip,
  getTripJoinRequestStatus,
  // Community: Travel Groups
  createTravelGroup,
  updateTravelGroup,
  getTravelGroup,
  subscribePublicTravelGroups,
  subscribeGroupMembers,
  submitGroupJoinRequest,
  approveGroupJoinRequest,
  rejectGroupJoinRequest,
  removeGroupMember,
  leaveGroup,
  subscribeGroupJoinRequestsForOwner,
  subscribeMyGroupJoinRequests,
  getGroupJoinRequestStatus,
  // Community: Nearby Travelers
  upsertNearbyTraveler,
  deleteNearbyTraveler,
  subscribeNearbyTravelers,
  subscribeDestinationTravelers,
  // Community: Activity Feed
  addFeedItem,
  subscribeActivityFeed,
  deleteFeedItem,
  updateOwnerPhotoInCommunityDocs,
  // Community: Block / Report
  blockUser,
  unblockUser,
  subscribeBlockList,
  isBlocked,
  reportContent,
} from './src/firestore';
export {
  storage,
  uploadProfilePhotoBase64,
  uploadProfilePhoto,
  uploadJournalPhoto,
  uploadTripCoverPhoto,
  deleteTripCoverPhoto,
} from './src/storage';
export {
  directChatId,
  upsertUserLookup,
  searchUserByEmail,
  subscribeToDirectChats,
  getOrCreateDirectChat,
  subscribeToDirectMessages,
  sendDirectMessage,
  markDirectChatRead,
  subscribeToGroups,
  createGroup,
  subscribeToGroupMessages,
  sendGroupMessage,
  markGroupRead,
  getGroup,
} from './src/chat';
